--blob=fake_discord_1:@/opt/zapret2/files/fake/quic_initial_dbankcloud_ru.bin
--blob=seqovl_pattern_2:@/opt/zapret2/files/fake/tls_clienthello_www_google_com.bin
--filter-tcp=80,443,2053,2083,2087,2096,8443
--filter-udp=443,19294-19344,50000-50100
--filter-udp=443
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=11:blob=fake_default_quic

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=discord
--lua-desync=fake:repeats=6:blob=fake_discord_1

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=stun
--lua-desync=fake:repeats=6:blob=fake_discord_1

--new
--filter-tcp=2053,2083,2087,2096,8443
--hostlist-domains=discord.media
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_seq=10000000:repeats=8:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=multisplit:tcp_seq=10000000:repeats=8:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_2:blob=fake_default_tls

--new
--filter-tcp=443
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_seq=10000000:ip_id=zero:repeats=8:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=multisplit:tcp_seq=10000000:ip_id=zero:repeats=8:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_2:blob=fake_default_tls

--new
--filter-tcp=80,443
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_seq=10000000:repeats=8:blob=fake_default_http:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=multisplit:tcp_seq=10000000:repeats=8:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_2:blob=fake_default_http

--new
--filter-udp=443
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=11:blob=fake_default_quic

--new
--filter-tcp=80,443,8443
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_seq=10000000:repeats=8:blob=fake_default_http:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=multisplit:tcp_seq=10000000:repeats=8:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_2:blob=fake_default_http

--new
--out-range=<n3
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_seq=10000000:repeats=8:payload=~empty:blob=fake_default_http:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=multisplit:tcp_seq=10000000:repeats=8:payload=~empty:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_2:blob=fake_default_http

--new
--out-range=<n2
--lua-desync=fake:repeats=10:payload=~empty:blob=fake_discord_1
