--blob=fake_quic_1:@/opt/zapret2/files/fake/quic_initial_www_google_com.bin
--blob=fake_discord_2:@/opt/zapret2/files/fake/quic_initial_dbankcloud_ru.bin
--blob=seqovl_pattern_3:@/opt/zapret2/files/fake/tls_clienthello_www_google_com.bin
--filter-tcp=80,443,2053,2083,2087,2096,8443
--filter-udp=443,19294-19344,50000-50100
--filter-udp=443
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_quic_1

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=discord
--lua-desync=fake:repeats=6:blob=fake_discord_2

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=stun
--lua-desync=fake:repeats=6:blob=fake_discord_2

--new
--filter-tcp=2053,2083,2087,2096,8443
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_3:blob=fake_default_tls

--new
--filter-tcp=443
--ip-id=zero
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_3:blob=fake_default_tls

--new
--filter-tcp=80,443
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_3:blob=fake_default_tls

--new
--filter-udp=443
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_quic_1

--new
--filter-tcp=80,443,8443
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_3:blob=fake_default_tls

--new
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=seqovl_pattern_3

--new
--lua-desync=fake:repeats=12:blob=fake_discord_2

# WARNINGS:
# manual-cutoff:n3
# manual-cutoff:n2
