--blob=fake_quic_1:@/opt/zapret2/files/fake/quic_initial_www_google_com.bin
--blob=fake_discord_2:@/opt/zapret2/files/fake/quic_initial_dbankcloud_ru.bin
--blob=fake_http_3:@/opt/zapret2/files/fake/tls_clienthello_max_ru.bin
--filter-tcp=80,443,2053,2083,2087,2096,8443
--filter-udp=443,19294-19344,50000-50100
--filter-udp=443
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_quic_1

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=discord
--lua-desync=fake:repeats=6:blob=fake_discord_2

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=stun
--lua-desync=fake:repeats=6:blob=fake_discord_2

--new
--filter-tcp=2053,2083,2087,2096,8443
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=hostfakesplit:tcp_ts_up:host=host=www.google.com,altorder=1:blob=fake_default_tls

--new
--filter-tcp=443
--ip-id=zero
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=hostfakesplit:tcp_ts_up:host=host=www.google.com,altorder=1:blob=fake_default_tls

--new
--filter-tcp=80,443
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_ts_up:blob=fake_http_3:tls_mod=rnd,dupsid,sni=ya.ru
--lua-desync=hostfakesplit:tcp_ts_up:host=host=ya.ru,altorder=1:blob=fake_http_3

--new
--filter-udp=443
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_quic_1

--new
--filter-tcp=80,443,8443
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_ts_up:blob=fake_http_3:tls_mod=rnd,dupsid,sni=ya.ru
--lua-desync=hostfakesplit:tcp_ts_up:host=host=ya.ru,altorder=1:blob=fake_http_3

--new
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_ts_up:blob=fake_http_3:tls_mod=rnd,dupsid,sni=ya.ru
--lua-desync=hostfakesplit:tcp_ts_up:host=host=ya.ru,altorder=1:blob=fake_http_3

--new
--lua-desync=fake:repeats=10:blob=fake_discord_2

# WARNINGS:
# manual-cutoff:n4
# manual-cutoff:n4
# manual-cutoff:n4
