--blob=fake_discord_1:@/opt/zapret2/files/fake/quic_initial_dbankcloud_ru.bin
--filter-tcp=80,443,2053,2083,2087,2096,8443
--filter-udp=443,19294-19344,50000-50100
--filter-udp=443
--hostlist=/opt/zapret2/ipset/list-general.txt
--hostlist=/opt/zapret2/ipset/list-general-user.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude-user.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_default_quic

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=discord
--lua-desync=fake:repeats=6:blob=fake_discord_1

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=stun
--lua-desync=fake:repeats=6:blob=fake_discord_1

--new
--filter-tcp=2053,2083,2087,2096,8443
--hostlist-domains=discord.media
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=hostfakesplit:tcp_ts_up:host=host=www.google.com,altorder=1:blob=fake_default_tls

--new
--filter-tcp=443
--hostlist=/opt/zapret2/ipset/list-google.txt
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:ip_id=zero:blob=fake_default_tls:tls_mod=rnd,dupsid,sni=www.google.com
--lua-desync=hostfakesplit:tcp_ts_up:ip_id=zero:host=host=www.google.com,altorder=1:blob=fake_default_tls

--new
--filter-tcp=80,443
--hostlist=/opt/zapret2/ipset/list-general.txt
--hostlist=/opt/zapret2/ipset/list-general-user.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude-user.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_ts_up:blob=fake_default_http:tls_mod=rnd,dupsid,sni=ya.ru
--lua-desync=hostfakesplit:tcp_ts_up:host=host=ya.ru,altorder=1:blob=fake_default_http

--new
--filter-udp=443
--ipset=/opt/zapret2/ipset/ipset-all.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude-user.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_default_quic

--new
--filter-tcp=80,443,8443
--ipset=/opt/zapret2/ipset/ipset-all.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude-user.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_ts_up:blob=fake_default_http:tls_mod=rnd,dupsid,sni=ya.ru
--lua-desync=hostfakesplit:tcp_ts_up:host=host=ya.ru,altorder=1:blob=fake_default_http

--new
--ipset=/opt/zapret2/ipset/ipset-all.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--out-range=<n4
--filter-l7=http
--payload=http_req
--lua-desync=fake:tcp_ts_up:payload=~empty:blob=fake_default_http:tls_mod=rnd,dupsid,sni=ya.ru
--lua-desync=hostfakesplit:tcp_ts_up:payload=~empty:host=host=ya.ru,altorder=1:blob=fake_default_http

--new
--ipset=/opt/zapret2/ipset/ipset-all.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--out-range=<n4
--lua-desync=fake:repeats=10:payload=~empty:blob=fake_discord_1
