--blob=fake_discord_1:@/opt/zapret2/files/fake/quic_initial_dbankcloud_ru.bin
--filter-tcp=80,443,2053,2083,2087,2096,8443
--filter-udp=443,19294-19344,50000-50100
--filter-udp=443
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_default_quic

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=discord
--lua-desync=fake:repeats=6:blob=fake_discord_1

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=stun
--lua-desync=fake:repeats=6:blob=fake_discord_1

--new
--filter-tcp=2053,2083,2087,2096,8443
--hostlist-domains=discord.media
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:blob=fake_default_tls

--new
--filter-tcp=443
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:ip_id=zero:repeats=6:blob=fake_default_tls

--new
--filter-tcp=80,443
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:blob=fake_default_tls

--new
--filter-udp=443
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_default_quic

--new
--filter-tcp=80,443,8443
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:blob=fake_default_tls

--new
--out-range=<n5
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:payload=~empty:blob=fake_default_tls

--new
--out-range=<n3
--lua-desync=fake:repeats=12:payload=~empty:blob=fake_discord_1

# WARNINGS:
# profile-5:duplicate-dpi-option:--dpi-desync-fake-tls=/opt/zapret2/files/fake/stun.bin,/opt/zapret2/files/fake/tls_clienthello_max_ru.bin
# profile-7:duplicate-dpi-option:--dpi-desync-fake-tls=/opt/zapret2/files/fake/stun.bin,/opt/zapret2/files/fake/tls_clienthello_max_ru.bin
# profile-8:duplicate-dpi-option:--dpi-desync-fake-tls=/opt/zapret2/files/fake/stun.bin,/opt/zapret2/files/fake/tls_clienthello_max_ru.bin
