--blob=fake_quic_1:@/opt/zapret2/files/fake/quic_initial_www_google_com.bin
--blob=fake_discord_2:@/opt/zapret2/files/fake/quic_initial_dbankcloud_ru.bin
--blob=fake_tls_3:@/opt/zapret2/files/fake/tls_clienthello_www_google_com.bin
--blob=fake_tls_4:@/opt/zapret2/files/fake/tls_clienthello_4pda_to.bin
--filter-udp=443
--hostlist=/opt/zapret2/ipset/list-general.txt
--hostlist=/opt/zapret2/ipset/list-general-user.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude-user.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_quic_1

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=discord
--payload=unknown_udp
--lua-desync=fake:repeats=6:blob=fake_discord_2

--new
--filter-udp=19294-19344,50000-50100
--filter-l7=stun
--payload=unknown_udp
--lua-desync=fake:repeats=6:blob=fake_discord_2

--new
--filter-tcp=2053,2083,2087,2096,8443
--hostlist-domains=discord.media
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:blob=fake_tls_3:tls_mod=none

--new
--filter-tcp=443
--hostlist=/opt/zapret2/ipset/list-google.txt
--ip-id=zero
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:blob=fake_tls_3

--new
--filter-tcp=80,443
--hostlist=/opt/zapret2/ipset/list-general.txt
--hostlist=/opt/zapret2/ipset/list-general-user.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude-user.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:blob=fake_tls_4

--new
--filter-udp=443
--ipset=/opt/zapret2/ipset/ipset-all.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude-user.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=quic
--payload=quic_initial
--lua-desync=fake:repeats=6:blob=fake_quic_1

--new
--filter-tcp=80,443,8443
--ipset=/opt/zapret2/ipset/ipset-all.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude.txt
--hostlist-exclude=/opt/zapret2/ipset/list-exclude-user.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:blob=fake_tls_4

--new
--ipset=/opt/zapret2/ipset/ipset-all.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--filter-l7=tls
--payload=tls_client_hello
--lua-desync=fake:tcp_ts_up:repeats=6:blob=fake_tls_4

--new
--ipset=/opt/zapret2/ipset/ipset-all.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude.txt
--ipset-exclude=/opt/zapret2/ipset/ipset-exclude-user.txt
--payload=unknown_udp
--lua-desync=fake:repeats=12:blob=fake_discord_2

# WARNINGS:
# profile-5:duplicate-dpi-option:--dpi-desync-fake-tls=/opt/zapret2/files/fake/stun.bin,/opt/zapret2/files/fake/tls_clienthello_4pda_to.bin
# profile-7:duplicate-dpi-option:--dpi-desync-fake-tls=/opt/zapret2/files/fake/stun.bin,/opt/zapret2/files/fake/tls_clienthello_4pda_to.bin
# profile-8:duplicate-dpi-option:--dpi-desync-fake-tls=/opt/zapret2/files/fake/stun.bin,/opt/zapret2/files/fake/tls_clienthello_4pda_to.bin
# manual-cutoff:n3
# manual-cutoff:n2
