--filter-tcp=443
--filter-l7=tls
--out-range=-d10
--payload=tls_client_hello
--lua-desync=fake:blob=fake_default_tls:ip_ttl=1:ip6_ttl=1:tls_mod=rnd,rndsni,padencap:repeats=11
--lua-desync=multidisorder:pos=1,midsld

--new
--filter-udp=443
--filter-l7=quic
--out-range=-d10
--payload=quic_initial
--lua-desync=fake:blob=fake_default_quic:repeats=11

--new
--filter-tcp=80
--filter-l7=http
--out-range=-d10
--payload=http_req
--lua-desync=fake:blob=fake_default_http:ip_ttl=1:ip6_ttl=1:repeats=11
--lua-desync=fakedsplit:pos=1,midsld

--new
--filter-l7=stun,discord
--payload=stun,discord_ip_discovery
--lua-desync=fake:blob=0x00000000000000000000000000000000:repeats=11

--new
--filter-udp=50000-50100
--out-range=<n2
--lua-desync=fake:blob=0x00:payload=~empty:repeats=10
